accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('register/', views.UserRegisterView.as_view(), name='user_register'),
	path('login/', views.UserLoginView.as_view(), name='user_login'),
	path('logout/', views.UserLogoutView.as_view(), name='user_logout'),
	path('profile/<int:pk>', views.UserProfileView.as_view(), name='user-profile'),

]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('user/', include('accounts.urls', namespace='accounts')),
    path('', include('projects.urls', namespace='projects')),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from .managers import UserManager


class User(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(max_length=255, unique=True)
    phone_number = models.CharField(max_length=11, unique=True)
    full_name = models.CharField(max_length=100)
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)
    is_professor = models.BooleanField(default=False)

    objects = UserManager()

    USERNAME_FIELD = 'phone_number'
    REQUIRED_FIELDS = ['email', 'full_name']

    def __str__(self):
        return self.email

    @property
    def is_staff(self):
        return self.is_admin

accounts/forms.py
from django import forms
from .models import User
from django.core.exceptions import ValidationError
from django.contrib.auth.forms import ReadOnlyPasswordHashField


class UserCreationForm(forms.ModelForm):
	password1 = forms.CharField(label='password', widget=forms.PasswordInput)
	password2 = forms.CharField(label='confirm password', widget=forms.PasswordInput)

	class Meta:
		model = User
		fields = ('email', 'phone_number', 'full_name', 'is_professor')

	def clean_password2(self):
		cd = self.cleaned_data
		if cd['password1'] and cd['password2'] and cd['password1'] != cd['password2']:
			raise ValidationError('passwords dont match')
		return cd['password2']

	def save(self, commit=True):
		user = super().save(commit=False)
		user.set_password(self.cleaned_data['password1'])
		if commit:
			user.save()
		return user


class UserChangeForm(forms.ModelForm):
	password = ReadOnlyPasswordHashField(help_text="you can change password using <a href=\"../password/\">this form</a>.")

	class Meta:
		model = User
		fields = ('email', 'phone_number', 'full_name', 'password', 'last_login')


class UserRegistrationForm(forms.Form):
	email = forms.EmailField()
	full_name = forms.CharField(label='full name')
	phone = forms.CharField(max_length=11)
	# is_professor = forms.CheckboxInput()

	password = forms.CharField(widget=forms.PasswordInput)

	def clean_email(self):
		email = self.cleaned_data['email']
		user = User.objects.filter(email=email).exists()
		if user:
			raise ValidationError('This email already exists')
		return email

	def clean_phone(self):
		phone = self.cleaned_data['phone']
		user = User.objects.filter(phone_number=phone).exists()
		if user:
			raise ValidationError('This phone number already exists')
		
		return phone


class VerifyCodeForm(forms.Form):
	code = forms.IntegerField()


class UserLoginForm(forms.Form):
	phone = forms.CharField()
	password = forms.CharField(widget=forms.PasswordInput)

accounts/views.py
from django.shortcuts import render, redirect
from django.views import View
from django.views.generic import TemplateView

from .forms import UserRegistrationForm, VerifyCodeForm, UserLoginForm
import random
from .models import  User
from django.contrib import messages
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.mixins import LoginRequiredMixin


# Create your views here.
class UserRegisterView(View):
    form_class = UserRegistrationForm
    template_name = 'accounts/register.html'

    def get(self, request):
        form = self.form_class
        return render(request, self.template_name, {'form':form})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            
            User.objects.create_user(cd['phone'], cd['email'],
                                         cd['full_name'], cd['password'])

            messages.success(request, 'You registered succesfully', 'success')
            return redirect('projects:projects')
        return render(request, self.template_name, {'form':form})


class UserLogoutView(LoginRequiredMixin, View):
    def get(self, request):
        logout(request)
        messages.success(request, 'you logged out successfully', 'success')
        return redirect('projects:projects')


class UserLoginView(View):
    form_class = UserLoginForm
    template_name = 'accounts/login.html'

    def get(self, request):
        form = self.form_class
        return render(request, self.template_name, {'form':form})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(request, phone_number=cd['phone'], password=cd['password'])
            if user is not None:
                login(request, user)
                messages.success(request, 'you logged in successfully', 'info')
                return redirect('projects:projects')
            messages.error(request, 'phone or password is wrong', 'warning')
        return render(request, self.template_name, {'form':form})


class UserProfileView(TemplateView):
    template_name = 'accounts/profile.html'

accounts/templates/accounts/login.html
{% extends 'base.html' %} {% load static %} {% block content %}

<div class="auth">
  <div class="card">
    <div class="auth__header text-center">
      <a href="/">
        <img src="{% static 'images/icon.svg' %}" alt="icon" />
      </a>
      <h3>Account Login</h3>
      <p>Hello Developer, Welcome Back!</p>
    </div>

    <form action="" method="POST" class="form auth__form">
      {% csrf_token %}
      <!-- Input:Username -->
      <div class="form__field">
        <label for="formInput#text">phone number: </label>
        <input
          class="input input--text"
          id="formInput#text"
          type="text"
          name="phone"
          placeholder="Enter your phone number..."
        />
      </div>

      <!-- Input:Password -->
      <div class="form__field">
        <label for="formInput#password">Password: </label>
        <input
          class="input input--password"
          id="formInput#passowrd"
          type="password"
          name="password"
          placeholder="••••••••"
        />
      </div>

      <div class="auth__actions">
        <input class="btn btn--sub btn--lg" type="submit" value="Log In" />
        <a href="#">Forget Password?</a>
      </div>
    </form>

    <div class="auth__alternative">
      <p>Don’t have an Account?</p>
      <a href="{% url 'accounts:user_register' %}">Sign Up</a>
    </div>
  </div>
</div>
{% endblock %}

accounts/templates/accounts/register.html
{% extends 'base.html' %} {% load static %} {% block content %}

<div class="auth">
  <div class="card">
    <div class="auth__header text-center">
      <a href="/">
        <img src="{% static 'images/icon.svg' %}" alt="icon" />
      </a>
      <h3>Register an Account</h3>
      <p>Create a new developer account</p>
    </div>

    <form method="POST" action="" class="form auth__form">
      {% csrf_token %} {% for field in form %}
      <div class="form__field">
        <label for="formInput#text">{{field.label}}</label>
        {{field}}

        <!-- {% if field.help_text %}
                <small>{{field.help_text}}</small>
                {% endif %} -->

        {% for error in field.errors %}
        <p style="color: red">{{error}}</p>
        {% endfor %}
      </div>

      {% endfor %}

      <div class="auth__actions">
        <input class="btn btn--sub btn--lg" type="submit" value="Sign  In" />
      </div>
    </form>
    <div class="auth__alternative">
      <p>Already have an Account?</p>
      <a href="{% url 'accounts:user_login' %}">Log In</a>
    </div>
  </div>
</div>
{% endblock %}