accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('register/', views.UserRegisterView.as_view(), name='user_register'),
	path('login/', views.UserLoginView.as_view(), name='user_login'),
	path('logout/', views.UserLogoutView.as_view(), name='user_logout'),
	path('profile/<int:pk>', views.UserProfileView.as_view(), name='user-profile'),

]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('user/', include('accounts.urls', namespace='accounts')),
    path('', include('projects.urls', namespace='projects')),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

projects/urls.py
from django.urls import path
from . import views

app_name = 'projects'
urlpatterns = [
    path('', views.ProjectsView.as_view(), name='projects'),
    path('<int:pk>/', views.ProjectDetailView.as_view(), name='project'),
    path('update/<int:pk>/', views.ProjectUpdateView.as_view(), name='update-project'),
    path('task/<int:pk>', views.TaskDetailsView.as_view(), name='task-details'),
    path('task/<int:pk>/completed', views.TaskCompleteView.as_view(), name='update-task-complete'),
    
]

templates/includes/navbar.html
{% load static %}

<!-- Header Section -->
<header class="header">
  <div class="container container--narrow">
    <a href="#" class="header__logo">
      <img src="{% static 'images/logo.svg' %} " alt="DevSearch Logo" />
    </a>

    <nav class="header__nav">
      <input type="checkbox" id="responsive-menu" />
      <label for="responsive-menu" class="toggle-menu">
        <span>Menu</span>
        <div class="toggle-menu__lines"></div>
      </label>
      <ul class="header__menu">
        {% if request.user.is_authenticated %} {% if request.user.is_staff %}
        <li class="header__menuItem">
          <a href="{% url 'admin:index' %}">Dashboard</a>
        </li>
        {% endif %}
        <li class="header__menuItem">
          <a href="{% url 'projects:projects' %}">Projects</a>
        </li>

        <li class="header__menuItem">
          <a href="{% url 'accounts:user_logout' %}" class="btn btn--sub"
            >Logout</a
          >
        </li>
        {% else %}
        <li class="header__menuItem">
          <a href="{% url 'accounts:user_login' %}" class="btn btn--sub"
            >Login/Sign Up</a
          >
        </li>
        {% endif %}
      </ul>
    </nav>
  </div>
</header>