accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('register/', views.UserRegisterView.as_view(), name='user_register'),
	path('login/', views.UserLoginView.as_view(), name='user_login'),
	path('logout/', views.UserLogoutView.as_view(), name='user_logout'),
	path('profile/<int:pk>', views.UserProfileView.as_view(), name='user-profile'),

]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('user/', include('accounts.urls', namespace='accounts')),
    path('', include('projects.urls', namespace='projects')),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

projects/urls.py
from django.urls import path
from . import views

app_name = 'projects'
urlpatterns = [
    path('', views.ProjectsView.as_view(), name='projects'),
    path('<int:pk>/', views.ProjectDetailView.as_view(), name='project'),
    path('update/<int:pk>/', views.ProjectUpdateView.as_view(), name='update-project'),
    path('task/<int:pk>', views.TaskDetailsView.as_view(), name='task-details'),
    path('task/<int:pk>/completed', views.TaskCompleteView.as_view(), name='update-task-complete'),
    
]

projects/models.py
from django.db import models
from accounts.models import User

# Create your models here.
class Project(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField(null=True, blank=True)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)

class Task(models.Model):
    assigned_to = models.ForeignKey(User, on_delete=models.CASCADE)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    description = models.TextField()
    completed = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

class Review(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    task = models.ForeignKey(Task, on_delete=models.CASCADE)
    reviewer = models.ForeignKey(User, on_delete=models.CASCADE)
    feedback = models.TextField()
    reply = models.ForeignKey('self', on_delete=models.CASCADE, related_name='rcomments', blank=True, null=True)
    is_reply = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)

projects/forms.py
from django import forms
from .models import Project, Task

class ProjectUpdateForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = ['title', 'description']

class ProjectCreationForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = ['title', 'description']

class TaskCreateForm(forms.ModelForm):
    user_id = forms.CharField()

    class Meta:
        model = Task
        fields = ['title', 'description']

projects/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views import View
from django.views.generic.edit import UpdateView
from django.urls import reverse_lazy
from .models import Project, Task
from .forms import ProjectUpdateForm, ProjectCreationForm, TaskCreateForm
from accounts.models import User
# Create your views here.

class ProjectsView(View):
    template_name = 'projects/projects.html'

    def get(self, request, *args, **kwargs):
        # Get the projects created by the current user
        user_projects = Project.objects.filter(created_by=request.user)

        # Pass the user_projects to the template
        context = {
            'projects': user_projects
        }

        # Render the template with the context
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        project_creation_form = ProjectCreationForm(request.POST)

        if project_creation_form.is_valid():
            # Save the new project with the current user as the creator
            new_project = project_creation_form.save(commit=False)
            new_project.created_by = request.user
            new_project.save()

            return redirect('projects:projects')  # Redirect to the projects page or any other desired page upon successful project creation
        else:
            # If the form is not valid, render the template again with the form and display validation errors
            user_projects = Project.objects.filter(created_by=request.user)
            context = {
                'projects': user_projects,
                'project_creation_form': project_creation_form,
            }
            return render(request, self.template_name, context)

class ProjectDetailView(View):
    template_name = 'projects/single-project.html'
    form_class = TaskCreateForm

    def get(self, request, *args, **kwargs):
        # Get the project by its ID or return a 404 response if not found
        project = get_object_or_404(Project, id=self.kwargs['pk'])
        # Get tasks related to the project
        project_tasks = Task.objects.filter(project=project)

        # Pass the project and the form to the template
        context = {
            'project': project,
            'tasks': project_tasks,
            'form': self.form_class(),  # Pass the project to the form
        }

        # Render the template with the context
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        project = get_object_or_404(Project, id=self.kwargs['pk'])
        form = self.form_class(request.POST)

        if form.is_valid():
            # Save the new task with the current project
            new_task = form.save(commit=False)
            new_task.project = project
            user = get_object_or_404(User, id=form.cleaned_data['user_id'])
            new_task.assigned_to = user

            new_task.save()

            return redirect('projects:project', pk=project.pk)  # Redirect to the project detail page upon successful task creation
        else:
            # If the form is not valid, render the template again with the form and display validation errors
            context = {
                'project': project,
                'form': task_creation_form,
            }
            return render(request, self.template_name, context)

class ProjectUpdateView(UpdateView):
    model = Project
    form_class = ProjectUpdateForm  # Replace with the actual form you create for updating projects
    template_name = 'projects/project_form.html'  # Replace with the actual template path
    success_url = reverse_lazy('projects:projects')  # Redirect to user_projects page after successful update

    def form_valid(self, form):
        # Optionally, you can add logic here for additional processing when the form is valid
        return super().form_valid(form)

class TaskDetailsView(View):
    template_name = 'projects/task-details.html'

    def get(self, request, *args, **kwargs):
        # Get the project by its ID or return a 404 response if not found
        task = get_object_or_404(Task, id=self.kwargs['pk'])

        context = {
            'task': task,
        }

        # Render the template with the context
        return render(request, self.template_name, context)

class TaskCompleteView(View):
    def get(self, request, *args, **kwargs):
        task_id = self.kwargs.get('pk')
        task = get_object_or_404(Task, id=task_id)

        # Update the task's 'completed' field to True
        task.completed = True
        task.save()

        # Redirect back to the project detail page or any other desired page
        return redirect('projects:project', pk=task.project.pk)

projects/templates/projects/project_form.html
{% extends 'base.html' %} {% block content %}

<!-- Main Section -->
<main class="formPage my-xl">
  <div class="content-box">
    <div class="formWrapper">
      <form class="form" method="POST" enctype="multipart/form-data">
        {% csrf_token %} {% for field in form %}
        <!-- Input:Text -->
        <div class="form__field">
          <label for="formInput#text">{{field.label}}</label>
          {{field}}
        </div>
        {% endfor %}

        <input
          class="btn btn--sub btn--lg my-md"
          type="submit"
          value="Submit"
        />
      </form>
    </div>
  </div>
</main>

{% endblock %}

projects/templates/projects/projects.html
{% extends 'base.html' %} {% block content %}

<!-- Main Section -->
<main class="projects">
  <section class="hero-section text-center">
    <div class="container container--narrow">
      <div class="hero-section__box">
        <h2>See Your <span>Projects</span></h2>
      </div>
      {% if request.user.is_professor %}
      <div class="hero-section__search">
        <form id="searchForm" class="form" action="" method="post">
          {% csrf_token %}
          <div class="form__field">
            <label for="formInput#search">Create New Project </label>
            <input
              class="input input--text"
              id="formInput#search"
              type="text"
              name="title"
              placeholder="Search by Project Title"
            />
          </div>

          <input class="btn btn--sub btn--lg" type="submit" value="Submit" />
        </form>
      </div>
      {% endif %}
    </div>
  </section>
  <!-- Search Result: DevList -->
  <section class="projectsList">
    <div class="container">
      <div class="grid grid--three">
        {% for project in projects %}
        <div class="column">
          <div class="card project">
            <a href="{% url 'projects:project' project.id %}" class="project">
              <div class="card__body">
                <h3 class="project__title">{{project.title}}</h3>
                <p>
                  <a class="project__author" href="#"
                    >By {{project.created_by.full_name}}</a
                  >
                </p>
              </div>
            </a>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </section>
</main>

{% endblock %}

projects/templates/projects/single-project.html
{% extends 'base.html' %}

{% block content %}

<!-- Main Section -->
<main class="singleProject my-md">
    <div class="container">
        <div class="layout">
            <div class="column column--1of3">
                <div class="card text-center">
                    <div class="card__body dev">
                        
                        {% if request.user.id == project.created_by.id %}
                        <a href="{% url 'projects:update-project' project.id %}" class="btn btn--sub btn--lg">Update Project </a>
                        {% comment %} <a href="{% url 'projects:create-task' %}" class="btn btn--sub btn--lg">Create Task </a> {% endcomment %}

                        {% endif %}
                    </div>
                </div>
            </div>
            <div class="column column--2of3">
                <a href="{% url 'accounts:user-profile' project.created_by.id  %}"
                    class="singleProject__developer">{{project.created_by.full_name}}</a>
                <h2 class="singleProject__title">{{project.title}}</h2>
                <h3 class="singleProject__subtitle">About the Project</h3>
                <div class="singleProject__info">
                    {{project.description}}
                </div>
                <div class="comments">
                    
                    {% if request.user.is_authenticated %}
                    <form class="form" action="" method="POST">
                        {% csrf_token %}
                        <div class="form__field">
                            <label for="formInput#text">assign to: </label>
                            <input
                              class="input input--text"
                              id="formInput#text"
                              type="text"
                              name="user_id"
                              placeholder="Enter person's id..."
                            />
                          </div>

                          <div class="form__field">
                            <label for="formInput#text">title: </label>
                            <input
                              class="input input--text"
                              id="formInput#text"
                              type="text"
                              name="title"
                              placeholder="Enter title of task..."
                            />
                          </div>
                          <div class="form__field">
                            <label for="formInput#text">description: </label>
                            <input
                              class="input input--text"
                              id="formInput#text"
                              type="text"
                              name="description"
                              placeholder="Enter description..."
                            />
                          </div>
                        
                        <input class="btn btn--sub btn--lg" type="submit" value="Add Task" />
                    </form>
                    {% else %}
                    <a href="{% url 'accounts:user_login' %}?next={{request.path}}">Please login to leave a review</a>
                    {% endif %}

                    <div class="devInfo">
                        <h3 class="devInfo__title">Tasks</h3>
                        <div class="grid grid--two">
                            {% for task in tasks %}
                            <div class="column">
                                <div class="card project">
                                    <a href="{% url 'projects:task-details' task.id %}" class="project">
                                        
                                        <div class="card__body">
                                            <h3 class="project__title">{{task.title}}</h3>
                                            
                                        </div>
                                    </a>
                                </div>
                            </div>
                            {% endfor %}
    
    
                        </div>
                    </div>

                    {% comment %} <div class="commentList">
                        {% for review in project.review_set.all %}
                        {% if review.body %}
                        <div class="comment">
                            <a href="{% url 'user-profile' review.reviewer.id  %}">
                                <img class="avatar avatar--md" src="{{review.owner.profile_image.url}}" alt="user" />
                            </a>


                            <div class="comment__details">
                                <a href="{% url 'user-profile' review.owner.id  %}"
                                    class="comment__author">{{review.reviewer.full_name}}</a>
                                <p class="comment__info">{{review.feedback|linebreaksbr}}</p>
                            </div>

                        </div>
                        {% endif %}
                        {% endfor %}

                    </div> {% endcomment %}
                </div>
            </div>
        </div>
    </div>
    </div>
</main>

{% endblock %}

projects/templates/projects/task-details.html
{% extends 'base.html' %}

{% block content %}

<main class="messagePage my-xl">
    <div class="content-box">
      <div class="message">
        <a class="backButton" href="inbox.html"><i class="im im-angle-left"></i></a>
        <h2 class="message__subject">{{task.title}}</h4>
          <a href="profile.html" class="message__author">{{task.project.title}}</a>
          <p class="message__date">{{task.created}}</p>
          <div class="message__body">{{task.description}}
          </div>
      </div>
      <a href="{% url 'projects:update-task-complete' task.id %}" class="btn btn--sub btn--lg">Completed </a>

    </div>
  </main>
{% endblock %}